# render.yaml
services:
  - type: web
    name: laravel-docker-app
    runtime: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
    autoDeploy: true
    buildFilter:
      paths:
        - Dockerfile
        - docker/**
        - app/**
        - bootstrap/**
        - config/**
        - database/**
        - public/**
        - resources/**
        - routes/**
        - storage/**
        - vendor/**
        - .env
        - composer.json
        - composer.lock
