/** @type {import('tailwindcss').Config} */
module.exports = {
  presets: [require('nativewind/preset')],
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#011549',
        'on-primary': '#ffffff',
        'primary-container': '#1a2b5e',
        'on-primary-container': '#8494cd',
        'primary-fixed': '#dce1ff',
        'on-primary-fixed': '#03174b',
        'primary-fixed-dim': '#b5c4ff',
        'on-primary-fixed-variant': '#344478',
        secondary: '#006d43',
        'on-secondary': '#ffffff',
        'secondary-container': '#75f8b3',
        'on-secondary-container': '#007147',
        'secondary-fixed': '#78fbb6',
        'on-secondary-fixed': '#002111',
        'secondary-fixed-dim': '#59de9b',
        'on-secondary-fixed-variant': '#005232',
        tertiary: '#3d0004',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#64000a',
        'on-tertiary-container': '#ff5f5c',
        'tertiary-fixed': '#ffdad7',
        'on-tertiary-fixed': '#410004',
        'tertiary-fixed-dim': '#ffb3ae',
        'on-tertiary-fixed-variant': '#930014',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#f7f9fd',
        'on-background': '#191c1f',
        surface: '#f7f9fd',
        'surface-dim': '#d8dade',
        'surface-bright': '#f7f9fd',
        'surface-variant': '#e0e3e6',
        'on-surface': '#191c1f',
        'on-surface-variant': '#45464f',
        'surface-container': '#eceef2',
        'surface-container-low': '#f2f4f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e6e8ec',
        'surface-container-highest': '#e0e3e6',
        'inverse-surface': '#2d3134',
        'inverse-on-surface': '#eff1f5',
        'inverse-primary': '#b5c4ff',
        'surface-tint': '#4c5c92',
        outline: '#757680',
        'outline-variant': '#c5c6d1',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        xxl: '1.5rem',
      },
      fontFamily: {
        headline: ['Sora', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      keyframes: {
        'pulse-slow': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
      },
    },
  },
  plugins: [],
};