[program:laravel-queue-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/prince-kangbode/Mes_projets/projet_verification_de_presence/backend/artisan queue:work redis --queue=default,gemini-import --sleep=3 --tries=3 --max-time=3600 --memory=256
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=4
redirect_stderr=true
stdout_logfile=/home/prince-kangbode/Mes_projets/projet_verification_de_presence/backend/storage/logs/worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5

[program:laravel-queue-worker-gemini]
process_name=%(program_name)s_%(process_num)02d
command=php /home/prince-kangbode/Mes_projets/projet_verification_de_presence/backend/artisan queue:work redis --queue=gemini-import --sleep=5 --tries=3 --max-time=300 --memory=512
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/home/prince-kangbode/Mes_projets/projet_verification_de_presence/backend/storage/logs/worker-gemini.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5

[program:laravel-scheduler]
process_name=%(program_name)s_%(process_num)02d
command=php /home/prince-kangbode/Mes_projets/projet_verification_de_presence/backend/artisan schedule:work
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/home/prince-kangbode/Mes_projets/projet_verification_de_presence/backend/storage/logs/scheduler.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5

[program:laravel-horizon]
process_name=%(program_name)s
command=php /home/prince-kangbode/Mes_projets/projet_verification_de_presence/backend/artisan horizon
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/home/prince-kangbode/Mes_projets/projet_verification_de_presence/backend/storage/logs/horizon.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5